### ISSUE TITLE
【小建议】大佬可以把这个集成进寻空或胡桃吗

### ISSUE THREAD

**Issue by Ignareo** [lingkai5wu/getYsFurnitureList#1]
很实用也很好用的功能，大佬能不能跟寻空和胡桃的开发者联系下，把这集成进去

**Comment by lingkai5wu** [comment]
我完善一下README然后给他们留个Issues吧，这个项目很简单，应该不需要联系。

**Comment by lingkai5wu** [comment]
胡桃已提。
https://github.com/orgs/DGP-Studio/projects/2/views/1?pane=issue&itemId=19783410
