### ISSUE TITLE
必传参数

### ISSUE THREAD

**Issue by NEWBOY-YJC** [lingkai5wu/getYsFurnitureList#2]
必传参数中region是服务器
参考UIGF
https://uigf.org/zh/mihoyo-api-collection/other/id.html#%E5%90%AF%E5%8A%A8%E5%99%A8id%E4%B8%8Ekey
![Screenshot_20231003_235523_com.microsoft.emmx.jpg](https://github.com/lingkai5wu/getYsFurnitureList/assets/94227484/81010c7d-9fbe-4d74-88b5-65a73d004981)

**Comment by lingkai5wu** [comment]
感谢！
